### ISSUE TITLE
Remover o diagrama do esquema corrente do BD

### ISSUE THREAD

**Issue by foliveirafilho** [codemeistre/docs#7]
Uma vez que a lib [`typeorm-uml`](https://github.com/eugene-manuilov/typeorm-uml) parece não estar mais sendo mantida, não faz mais sentido manter este diagrama já que era gerado a partir da referida biblioteca.

Contudo, há uma PR em aberto que faz a migração para o TypeORM v0.3.0:
1. https://github.com/eugene-manuilov/typeorm-uml/pull/56

Podemos observá-la e verificar algum tipo de posicionamento do autor. Caso o mesmo não responda, creio que remover o diagrama do esquema corrente do BD seja o ideal.

**Comment by micalevisk** [comment]
se não tivermos retorno até o fim deste mês, removeremos ele.
